config/routes.rb
Rails.application.routes.draw do
  mount_at = Gluttonberg::Engine.config.mount_at

  scope :module => 'gluttonberg' do
    namespace :admin do
      root :to => "main#index"
      get "waiting-for-approval" => "main#waiting_for_approval" , :as => :waiting_for_approval
      get "decline-content/:object_class/:version_id" => "main#decline_content" , :as => :decline_content
      

      scope :module => 'content' do
        controller :auto_save do
          match "/autosave/:model_name/:id" => :create , :as => :autosave
          get "/remove_autosaved_version/:model_name/:id" => :destroy , :as => :remove_autosaved_version
          get "/retreive_changes/:model_name/:id" => :retreive_changes , :as => :retreive_changes
        end

        get "/flagged_contents" => "flag#index" , :as => :flagged_contents
        get '/flagged_contents/moderation/:id/:moderation' => "flag#moderation", :as => :flagged_contents_moderation

        resources :pages do
          member do
            get 'delete'
            get 'duplicate'
            get 'collapse'
            get 'expand'
          end
          collection do
            post 'move' =>  :move_node, :as => :move
            post 'update_home', :as =>  :update_home
            match 'import'
            get 'export'
            get 'collapse_all'
            get 'expand_all'
          end

          resources :page_localizations
        end
        get "pages_list_for_tinymce" => "pages#pages_list_for_tinymce" , :as => :pages_list_for_tinymce

        post "/pages/move(.:format)" => "pages#move_node" , :as=> :page_move
        resources :galleries do
          get 'delete', :on => :member
        end
        post "/galleries/move(.:format)" => "galleries#move_node" , :as=> :gallery_move

      end

      # Settings
      scope :module => 'settings' do
        get 'history' => "global_history#index",      :as => :global_history
        resources :locales do
          get 'delete', :on => :member
        end

        resources :users do
          get 'delete', :on => :member
        end

        resources :configurations do
          get 'delete', :on => :member
        end

        resources :stylesheets do
          get 'delete', :on => :member
        end
        post "/stylesheets/move(.:format)" => "stylesheets#move_node" , :as=> :stylesheet_move

        resources :embeds do
          get 'delete', :on => :member
          get 'list-for-redactor' => :list_for_redactor, :on => :collection
        end
      end

      namespace :membership do
        root :to =>  "main#index"
        post "/groups/move(.:format)" => "groups#move_node" , :as=> :group_move
        get "members/export" => "members#export" , :as => :members_export
        get 'members/new_bulk'  => "members#new_bulk" , :as => :members_import
        post 'members/create_bulk' => "members#create_bulk" , :as => :members_bulk_create
        resources :members do
          get 'delete', :on => :member
          get 'welcome' , :on => :member
          get 'group/:id' => "members#group", :on => :collection, :as => :group_members
        end
        resources :groups do
          get 'delete', :on => :member
        end
      end


      scope :module => 'asset_library' do
        # asset library related routes
        resources :assets do
          get 'delete', :on => :member
          get 'crop', :on => :member
          post 'save_crop', :on => :member
        end
        get "library" => "assets#index" , :as => :library
        get "search_assets" => "assets#search" , :as => :library_search
        post "add_asset_using_ajax"  => "assets_ajax#create" , :as => :add_asset_using_ajax
        get "add_assets_in_bulk"  => "assets_bulk#add_assets_in_bulk" , :as => :add_assets_in_bulk
        post "create_assets_in_bulk"  => "assets_bulk#create_assets_in_bulk" , :as => :create_assets_in_bulk
        post "destroy_assets_in_bulk"  => "assets_bulk#destroy_assets_in_bulk" , :as => :destroy_assets_in_bulk
        get "browser"  => "assets#browser" , :as => :asset_browser
        get "browser-collection/:id"  => "assets_ajax#browser_collection" , :as => :asset_browser_collection
        get "filter_assets_by_date"  => "assets_ajax#filter_assets_by_date" , :as => :filter_assets_by_date
        get "assets/:category/page/:page"  => "assets#category" , :as => :asset_category
        get "collections/:id/page/:page"  => "collections#show" , :as => :asset_collection
        resources :collections  do
          get 'delete', :on => :member
        end
      end

      resources :password_resets

      get "login" => "user_sessions#new", :as => :login
      post "login" => "user_sessions#create"
      get "logout" => "user_sessions#destroy", :as => :logout
    end

    scope :module => 'public' do
      get "/user_asset/:hash/:id(/:thumb_name)" => "public_assets#show" , :as => :public_asset
      get "/_public/page" => "pages#show"
      get "/restrict_site_access" => "pages#restrict_site_access" , :as => :restrict_site_access
      get "sitemap" => "pages#sitemap" , :as => :sitemap

      get "/mark_as_flag/:flaggable_type/:flaggable_id" => "flag#new" , :as => :mark_as_flag
      post "/save_mark_as_flag" => "flag#create" , :as => :save_mark_as_flag
      get "(/:locale)/member/login" => "member_sessions#new" , :as => :member_login
      post "(/:locale)/member/login" => "member_sessions#create"  , :as => :member_login
      get "(/:locale)/member/logout" => "member_sessions#destroy", :as => :member_logout
      get "(/:locale)/member/confirm/:key" => "members#confirm", :as => :member_confirmation
      get "(/:locale)/member/resend_confirmation" => "members#resend_confirmation", :as => :member_resend_confirmation
      put "(/:locale)/member/profile" => "members#update"
      get "(/:locale)/member/profile" => "members#show", :as => :member_profile
      get "(/:locale)/member/profile/edit" => "members#edit", :as => :member_profile_edit

      scope "(/:locale)" do
        resources :members
        resources :member_password_resets
      end

      get 'stylesheets/:id' => "pages#stylesheets", :as =>  :stylesheets
    end


  end

  scope :module => 'gluttonberg' do
    scope :module => 'public' do
      get "*a" => "pages#error_404"
    end
  end
end

app/controllers/gluttonberg/admin/asset_library/assets_ajax_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module AssetLibrary
      class AssetsAjaxController < Gluttonberg::Admin::AssetLibrary::BaseController
        # Create asset for ajax request from asset selector
        def create
          handle_blank_asset_name
          # process new asset_collection and merge into existing collections
          AssetCollection.process_new_collection_and_merge(params, current_user)
          prepare_new_asset_object
          if @asset.save
            render :text  => @asset.to_json_for_ajax_new.to_s
          else
            prepare_to_edit
            render :new
          end
        end

        # expand an asset collection
        def browser_collection
          @collection = AssetCollection.where(:id => params[:id]).first
          @category_filter =  params[:filter] || "all"
          @assets = AssetCategory.find_assets_by_category_and_collection(@category_filter, @collection)
          render :layout => false
        end

        # Filter assets by a selected date in asset selector
        def filter_assets_by_date
          unless params[:asset_date_filter].blank?
            date = Time.zone.parse(params[:asset_date_filter])
            @search_assets = Asset.where(["created_at between ? AND ?", date.beginning_of_day, date.end_of_day ] )
            respond_to do |format|
              format.html do
                @search_assets = @search_assets.paginate({
                  :per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"),
                  :page => params[:page]
                })
              end
              format.json do 
                render :template => "/gluttonberg/admin/asset_library/assets/search.json.haml"
              end
            end
          end
        end

        private
          def handle_blank_asset_name
            @blank_asset_name = false
            if params[:asset][:name].blank?
              params[:asset][:name] = "Asset #{Time.now.to_i}"
              @blank_asset_name = true
            end
          end

          def prepare_new_asset_object
            @asset = Asset.new(params[:asset])
            @asset.user_id = current_user.id
            @asset.name = @asset.file_name.humanize if @blank_asset_name
          end
      end
    end #AssetLibrary
  end
end

app/controllers/gluttonberg/admin/asset_library/assets_bulk_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module AssetLibrary
      class AssetsBulkController < Gluttonberg::Admin::AssetLibrary::BaseController
        record_history :@asset

        def destroy_assets_in_bulk
          @assets = Asset.where(:id => params[:asset_ids].split(",")).all
          @assets.each do |asset|
            authorize! :destroy, asset
            asset.destroy
          end
          redirect_to admin_asset_category_path(:category => 'all' , :page => 1 )
        end

        # add assets from zip folder
        def add_assets_in_bulk
          @asset = Asset.new
        end

        # create assets from zip
        def create_assets_in_bulk
          # process new asset_collection and merge into existing collections
          AssetCollection.process_new_collection_and_merge(params, current_user)
          @asset = Asset.new(params[:asset])
          if @asset.valid?
            @new_assets = AssetBulkImport.open_zip_file_and_make_assets(params[:asset], current_user)
            if @new_assets.blank?
              flash[:error] = "The zip file you uploaded does not have any valid files."
              prepare_to_edit
              render :action => :add_assets_in_bulk
            else
              flash[:notice] = "All valid assets have been successfully saved."
            end
          else
            prepare_to_edit
            flash[:error] = "The zip file you uploaded is not valid."
            render :action => :add_assets_in_bulk
          end
        end

      end # controller
    end
  end
end

app/controllers/gluttonberg/admin/asset_library/assets_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module AssetLibrary
      class AssetsController < Gluttonberg::Admin::AssetLibrary::BaseController
        before_filter :find_asset , :only => [:crop , :save_crop , :delete , :edit , :show , :update , :destroy  ]
        before_filter :authorize_user , :except => [:destroy , :delete]
        before_filter :authorize_user_for_destroy , :only => [:destroy , :delete]
        before_filter :authorize_user_for_edit , :only => [:edit , :update, :crop, :save_crop]

        record_history :@asset
        include Gluttonberg::ApplicationHelper

        # home page of asset library
        def index
          redirect_to admin_asset_category_path(:category => 'all' , :page => 1 )
        end


        def search
          unless params[:asset_query].blank?
            @search_assets = Asset.search_assets(clean_public_query(params[:asset_query]))
            respond_to do |format|
              format.html do
                @search_assets = @search_assets.paginate({
                  :per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"),
                  :page => params[:page]
                })
              end
              format.json
            end
          end
        end

        # if filter param is provided then it will only show filtered type
        def browser
          prepare_to_edit
          # Get the latest assets
          @category_filter = params[:filter] || "all"
          @assets = AssetCategory.find_assets_by_category(@category_filter).order("created_at DESC").limit(20)
          render(params["no_frame"] ? {:partial => "browser_root"} : {:layout => false})
        end

        # list assets page by page if user drill down into a category from category tab of home page
        def category
          params[:category] = params[:category].downcase.singularize unless params[:category].blank?
          params[:order_type] = params[:order_type] || "desc"
          @assets = AssetCategory.find_assets_by_category(params[:category])
          @assets = @assets.paginate({
            :per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"),
            :page => params[:page]
          }).order(get_order)
        end


        def show
        end

        # new asset
        def new
          @asset = Asset.new
        end

        def edit
        end

        def crop
          @image_type = params[:image_type]
          @image_type = @image_type.to_sym unless @image_type.blank?
        end

        def save_crop
          @asset.generate_cropped_image(params[:x] , params[:y] , params[:w] , params[:h] , params[:image_size])
          flash[:notice] = "New cropped image was successfully created"
          redirect_to :back
        end

        # delete asset
        def delete
          return_url = admin_asset_category_path(:category => 'all' , :page => 1 )
          return_url =  request.referrer unless request.referrer.blank?
          display_delete_confirmation(
            :title      => "Delete “#{@asset.name}” asset?",
            :url        => admin_asset_path(@asset),
            :return_url => return_url
          )
        end

        # create individual asset
        def create
          # process new asset_collection and merge into existing collections
          AssetCollection.process_new_collection_and_merge(params, current_user)

          @asset = Asset.new(params[:asset])
          @asset.user_id = current_user.id
          if @asset.save
            flash[:notice] = "The asset was successfully created."
            redirect_to(admin_asset_path(@asset))
          else
            prepare_to_edit
            render :new
          end
        end

        # update asset
        def update
          # process new asset_collection and merge into existing collections
          AssetCollection.process_new_collection_and_merge(params, current_user)

          if @asset.update_attributes(params[:asset])
            flash[:notice] = "The asset was successfully updated."
            redirect_to(admin_asset_path(@asset))
          else
            prepare_to_edit
            flash[:error] = "Sorry, The asset could not be updated."
            render :edit
          end
        end

        # destroy an indivdual asset
        def destroy
          if @asset.destroy
            flash[:notice] = "The asset was successfully deleted."
          else
            flash[:error] = "There was an error deleting the asset."
          end
          if params[:return_url].blank? && !params[:return_url].include?(admin_asset_path(params[:id]))
            redirect_to params[:return_url]
          else
            redirect_to admin_asset_category_path(:category => 'all' , :page => 1 )
          end
        end

        private
          def find_asset
            @asset = Asset.where(:id => params[:id]).first
            raise ActiveRecord::RecordNotFound if @asset.blank?
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Asset
          end

          def authorize_user_for_destroy
            authorize! :destroy, @asset
          end

          def authorize_user_for_edit
            authorize! :edit, @asset
          end

      end # controller
    end
  end
end

app/controllers/gluttonberg/admin/asset_library/base_controller.rb
module Gluttonberg
  module Admin
    module AssetLibrary
      class BaseController < Gluttonberg::Admin::BaseController
        before_filter :find_categories, :except => [:delete, :destroy]
        before_filter :prepare_to_edit  , :except => [:category , :show , :delete , :create , :update  ]
        before_filter :authorize_user, :except => [:destroy , :delete]
        before_filter :authorize_user_for_destroy , :only => [:destroy , :delete]

        protected
          def find_categories
            @categories = AssetCategory.all
          end

          def prepare_to_edit
            @collections = AssetCollection.order("name")
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Asset
          end

          def authorize_user_for_destroy
            authorize! :destroy, Gluttonberg::Asset
          end
      end
    end #AssetLibrary
  end
end

app/helpers/gluttonberg/asset_library.rb
module Gluttonberg
  module AssetLibrary

    # nice and clean public url of assets
    def asset_url(asset , opts = {})
      url = ""
      if Rails.configuration.asset_storage == :s3
        url = asset.url
      else
        url = "http://#{request.host_with_port}/user_asset/#{asset.asset_hash[0..3]}/#{asset.id}"
        if opts[:thumb_name]
          url << "/#{opts[:thumb_name]}"
        end
      end
      url
    end

    def asset_tag(asset , thumbnail_type = nil, options = {} )
      asset_tag_v2(asset , options, thumbnail_type)
    end

    def asset_tag_v2(asset , options = {} , thumbnail_type = nil)
      if !asset.blank? && asset.category == "image"
        _prepare_options_for_asset_tag(asset , options , thumbnail_type)
        tag("img" , options)
      end
    end

    private
      def _prepare_options_for_asset_tag(asset , options = {} , thumbnail_type = nil)
        options[:class] = (options[:class].blank? ? asset.name.to_s.sluglize : "#{options[:class]} #{asset.name.sluglize}" )
        options[:title] = asset.name  unless options.has_key?(:title)
        options[:alt] = asset.alt.blank? ? asset.name : asset.alt unless options.has_key?(:alt)
        options[:src] = asset.url_for(thumbnail_type)
      end

  end # Assets
end # Gluttonberg

app/views/gluttonberg/admin/asset_library/shared/_asset_browser.html.haml
%ul.thumbnails{:id => "title_thumb_#{opts[:id]}"}
  %li.span4
    %span.thumbnail.asset_selector_wrapper
      - unless asset.blank?
        - if asset.category && asset.category.to_s.downcase == "image"
          = asset_tag(asset , :small_thumb)
        - elsif asset.category && asset.category.to_s.downcase == "video"
          - unless asset.poster_image.blank?
            = asset_tag(asset.poster_image , :small_thumb)
      %span.caption
        - title = if opts[:asset_id].blank?
          - "Nothing selected"
        - elsif asset.blank?
          - "Asset missing!"
        - else
          - asset.name
        %h5{:title => title}
          = title

        = hidden_field_tag("filter_#{field_name}", opts[:filter] , :id => "filter_#{opts[:id]}" )
        - html_opts = { :id => opts[:id] , :class => "choose_asset_hidden_field" }
        - if defined?(form) && form
          = form.hidden_field(field_name , html_opts )
        - else
          = hidden_field_tag(field_name , opts[:asset_id], html_opts )

        %p
          = link_to("Select", "/admin/browser?filter=#{opts[:filter]}" , { :class =>"btn button choose_button #{opts[:button_class]}" , :rel => opts[:id], :style => "margin-right:5px;" , :data_url => opts[:data_url] })

          - if opts[:remove_button] != false
            - if defined?(form) && form
              = form.clear_asset( field_name , opts )
            - else
              = clear_asset_tag( field_name , opts )

app/views/gluttonberg/admin/asset_library/shared/_asset_panels.html.haml
- breadcrumbs_val = ""
- if defined?(previous_page_title) && !previous_page_title.blank?
  - breadcrumbs_val = "?previous_page_title=#{previous_page_title}&return_url=#{sorter_url}"
%table{:id => 'assets_table', :class => 'table table-bordered', :cellpadding => 0, :cellspacing => 0, :rel => "" , :summary => "Assets" }
  %thead
    %tr
      %th{:width => 20}
        - unless breadcrumbs_val.blank?
          = check_box_tag "select_asset_all" , nil, false , :class => "select_all_assets"
      %th{:width => 170}
      %th
        - if defined?(sorter_url)
          = sorter_link("Title",   "asset_name",   sorter_url )
        - else
          Title
      %th{:class => "author", :width => 80}
        File Type
      %th{:class => "date", :style => 'width:18%'}
        - if defined?(sorter_url)
          = sorter_link("Date added",   "date-added",   sorter_url )
        - else
          Date added

      %th{:style => 'width: 28%'}
  %tbody
    - if @assets.blank?
      %tr
        %td{:colspan => 6, :align => "center"}
          No assets
    - else
      - for asset in @assets
        %tr
          %td
            - if !breadcrumbs_val.blank? && can?(:destroy , asset)
              = check_box_tag "select_asset_#{asset.id}" , nil, false, :rel => "#{asset.id}" , :class => "select_asset_checkbox"
          %td
            - if asset.category == 'audio'
              .ui360
                %a{:href => "#{asset_url(asset)}", :target => "_blank" , :class => ""}
                  Play
            - elsif asset.category == 'image'
              %a{:href => admin_asset_url(asset), :class => "thumbnail"}
                %img{:src => asset.thumb_small_url  }
            - elsif asset.category == 'video'
              - unless asset.poster_image.blank?
                %a{:href => admin_asset_url(asset), :class => "thumbnail"}
                  %img{:src => asset.poster_image.thumb_small_url  }

          %td
            %a{:href => "#{admin_asset_url(asset)}#{breadcrumbs_val}", :class => "assetLink"}
              = asset.name
          %td.author
            = asset.asset_type.name
          %td.date
            = date_format(asset.created_at)
          %td.date
            %span.controls
              - unless breadcrumbs_val.blank?
                - if can? :edit , asset
                  %a{:href => "#{edit_admin_asset_url(asset)}#{breadcrumbs_val}" , :class => "assetLink btn"}
                    Edit
                  %a{:href => "#{crop_admin_asset_url(asset)}#{breadcrumbs_val}" , :class => "assetLink btn"}
                    Crop
                - if can? :destroy , asset
                  %a{:href => "#{delete_admin_asset_url(asset)}#{breadcrumbs_val}" , :class => "assetLink btn btn-danger"}
                    Delete

%a{:href => "#",  :class => "delete_selected_assets btn btn-danger"} Delete Selected Assets
%form#delete_selected_assets_form{ :action =>admin_destroy_assets_in_bulk_path , :method => "POST" }
  %input{ :type => "hidden" , :value =>"", :name => "asset_ids"}
- if @assets.respond_to?(:total_pages)
  = will_paginate(@assets)

app/views/gluttonberg/admin/asset_library/shared/_sidebar.html.haml
.span3
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header
        Library
      %li
        = active_link_to("Assets", admin_asset_category_path(:category => 'all' , :page => 1 ), :title => "Assets", :class => 'assets')
      %li
        = active_link_to("Collections", admin_collections_path, :title => "Collections", :class => 'collections')
      %li
        = active_link_to("Add asset", new_admin_asset_path, :title => "Add asset", :class => 'upload')

app/views/gluttonberg/admin/asset_library/shared/_sorter.html.haml
- unless @assets.empty?
  %p#sorterLabel Order by
  %ul#sorter
    %li#sortAdded
      =    sorter_link("Date added",   "date-added",   url)
    %li#sortUpdated
      =  sorter_link("Date updated", "date-updated", url)
    %li#sortName
      =     sorter_link("Name",         "name",         url)