config/routes.rb
Rails.application.routes.draw do
  mount_at = Gluttonberg::Engine.config.mount_at

  scope :module => 'gluttonberg' do
    namespace :admin do
      root :to => "main#index"
      get "waiting-for-approval" => "main#waiting_for_approval" , :as => :waiting_for_approval
      get "decline-content/:object_class/:version_id" => "main#decline_content" , :as => :decline_content
      

      scope :module => 'content' do
        controller :auto_save do
          match "/autosave/:model_name/:id" => :create , :as => :autosave
          get "/remove_autosaved_version/:model_name/:id" => :destroy , :as => :remove_autosaved_version
          get "/retreive_changes/:model_name/:id" => :retreive_changes , :as => :retreive_changes
        end

        get "/flagged_contents" => "flag#index" , :as => :flagged_contents
        get '/flagged_contents/moderation/:id/:moderation' => "flag#moderation", :as => :flagged_contents_moderation

        resources :pages do
          member do
            get 'delete'
            get 'duplicate'
            get 'collapse'
            get 'expand'
          end
          collection do
            post 'move' =>  :move_node, :as => :move
            post 'update_home', :as =>  :update_home
            match 'import'
            get 'export'
            get 'collapse_all'
            get 'expand_all'
          end

          resources :page_localizations
        end
        get "pages_list_for_tinymce" => "pages#pages_list_for_tinymce" , :as => :pages_list_for_tinymce

        post "/pages/move(.:format)" => "pages#move_node" , :as=> :page_move
        resources :galleries do
          get 'delete', :on => :member
        end
        post "/galleries/move(.:format)" => "galleries#move_node" , :as=> :gallery_move

      end

      # Settings
      scope :module => 'settings' do
        get 'history' => "global_history#index",      :as => :global_history
        resources :locales do
          get 'delete', :on => :member
        end

        resources :users do
          get 'delete', :on => :member
        end

        resources :configurations do
          get 'delete', :on => :member
        end

        resources :stylesheets do
          get 'delete', :on => :member
        end
        post "/stylesheets/move(.:format)" => "stylesheets#move_node" , :as=> :stylesheet_move

        resources :embeds do
          get 'delete', :on => :member
          get 'list-for-redactor' => :list_for_redactor, :on => :collection
        end
      end

      namespace :membership do
        root :to =>  "main#index"
        post "/groups/move(.:format)" => "groups#move_node" , :as=> :group_move
        get "members/export" => "members#export" , :as => :members_export
        get 'members/new_bulk'  => "members#new_bulk" , :as => :members_import
        post 'members/create_bulk' => "members#create_bulk" , :as => :members_bulk_create
        resources :members do
          get 'delete', :on => :member
          get 'welcome' , :on => :member
          get 'group/:id' => "members#group", :on => :collection, :as => :group_members
        end
        resources :groups do
          get 'delete', :on => :member
        end
      end


      scope :module => 'asset_library' do
        # asset library related routes
        resources :assets do
          get 'delete', :on => :member
          get 'crop', :on => :member
          post 'save_crop', :on => :member
        end
        get "library" => "assets#index" , :as => :library
        get "search_assets" => "assets#search" , :as => :library_search
        post "add_asset_using_ajax"  => "assets_ajax#create" , :as => :add_asset_using_ajax
        get "add_assets_in_bulk"  => "assets_bulk#add_assets_in_bulk" , :as => :add_assets_in_bulk
        post "create_assets_in_bulk"  => "assets_bulk#create_assets_in_bulk" , :as => :create_assets_in_bulk
        post "destroy_assets_in_bulk"  => "assets_bulk#destroy_assets_in_bulk" , :as => :destroy_assets_in_bulk
        get "browser"  => "assets#browser" , :as => :asset_browser
        get "browser-collection/:id"  => "assets_ajax#browser_collection" , :as => :asset_browser_collection
        get "filter_assets_by_date"  => "assets_ajax#filter_assets_by_date" , :as => :filter_assets_by_date
        get "assets/:category/page/:page"  => "assets#category" , :as => :asset_category
        get "collections/:id/page/:page"  => "collections#show" , :as => :asset_collection
        resources :collections  do
          get 'delete', :on => :member
        end
      end

      resources :password_resets

      get "login" => "user_sessions#new", :as => :login
      post "login" => "user_sessions#create"
      get "logout" => "user_sessions#destroy", :as => :logout
    end

    scope :module => 'public' do
      get "/user_asset/:hash/:id(/:thumb_name)" => "public_assets#show" , :as => :public_asset
      get "/_public/page" => "pages#show"
      get "/restrict_site_access" => "pages#restrict_site_access" , :as => :restrict_site_access
      get "sitemap" => "pages#sitemap" , :as => :sitemap

      get "/mark_as_flag/:flaggable_type/:flaggable_id" => "flag#new" , :as => :mark_as_flag
      post "/save_mark_as_flag" => "flag#create" , :as => :save_mark_as_flag
      get "(/:locale)/member/login" => "member_sessions#new" , :as => :member_login
      post "(/:locale)/member/login" => "member_sessions#create"  , :as => :member_login
      get "(/:locale)/member/logout" => "member_sessions#destroy", :as => :member_logout
      get "(/:locale)/member/confirm/:key" => "members#confirm", :as => :member_confirmation
      get "(/:locale)/member/resend_confirmation" => "members#resend_confirmation", :as => :member_resend_confirmation
      put "(/:locale)/member/profile" => "members#update"
      get "(/:locale)/member/profile" => "members#show", :as => :member_profile
      get "(/:locale)/member/profile/edit" => "members#edit", :as => :member_profile_edit

      scope "(/:locale)" do
        resources :members
        resources :member_password_resets
      end

      get 'stylesheets/:id' => "pages#stylesheets", :as =>  :stylesheets
    end


  end

  scope :module => 'gluttonberg' do
    scope :module => 'public' do
      get "*a" => "pages#error_404"
    end
  end
end

app/views/gluttonberg/admin/shared/_asset_panel.html.haml
- if assets.blank?
  - if type == "search"
    .alert
      Sorry, There were no search results found.
  - elsif @category_filter.blank? || @category_filter == "all"
    .alert
      Sorry, There are no assets added as yet.
  - else
    .alert
      Sorry, There are no
      %i
        = @category_filter
      added as yet.

- else
  %ul#assetPanels.thumbnails
    - for asset in assets
      %li.span3
        .thumbnail
          - if asset.category == 'audio'
            .sm2-inline-list
              .ui360
                %a{:href => "#{asset_url(asset)}", :target => "_blank" , :class => "no-ajax"}
                  = asset.name
          - elsif asset.category == 'image'
            %img{:src => "#{asset.thumb_small_url}"}
          - elsif asset.category && asset.category.to_s.downcase == "video"
            - unless asset.poster_image.blank?
              %img{:src => "#{asset.poster_image.thumb_small_url}"}
          .caption
            %h5{:class => (asset.category == 'image' || (asset.category == 'video' && !asset.poster_image.blank?) ? '' : 'asset-without-image' )}
              = asset.name
            %p
              = "#{asset.created_at.strftime("%d/%m/%y %I:%M %p")}"
            %p
              - if params[:open_link].blank?
                - if asset.category == "image" && !params[:size_selector].blank?
                  = select_tag nil, options_for_select(Rails.configuration.thumbnails.find_all{|key, val| val[:show_in_asset_picker] == true || key == :jwysiwyg_image}.collect{|key, val| [val[:label], asset.url_for(key)] }), {"data-title" => "#{asset.name}", :prompt => "Select Image Size", :class => "size_selector"}
                
                - elsif asset.category && asset.category == "video" && !asset.poster_image.blank?
                  %a{:href => "#{admin_asset_url(asset)}", :rel => "#{asset.category}", :class => "assetLink btn btn-primary" , "data-title" => "#{asset.name}" , "data-credits" => "#{asset.artist_name}" , "data-thumb" => "#{asset.poster_image.thumb_small_url}" , "data-jwysiwyg" => "#{(asset.category == "image" ? asset.url_for(:jwysiwyg_image) : asset.url)}" , "data-category" => "#{asset.category}"}
                    Select

                - else
                  %a{:href => "#{admin_asset_url(asset)}", :rel => "#{asset.category}", :class => "assetLink btn btn-primary" , "data-title" => "#{asset.name}" , "data-credits" => "#{asset.artist_name}" , "data-thumb" => "#{asset.thumb_small_url}" , "data-jwysiwyg" => "#{(asset.category == "image" ? asset.url_for(:jwysiwyg_image) : asset.url)}" , "data-category" => "#{asset.category}"}
                    Select
              - else
                %a{:href => "#{admin_asset_url(asset)}", :class => "assetLink btn btn-primary"}
                  Show



  - if assets.respond_to? :total_pages
    = will_paginate(assets)

app/views/gluttonberg/admin/shared/_auto_save_version.html.haml
.restore-auto-save
  %h4
    Unsaved changes
  %p
    It looks like previous edits you made to this page have not yet been saved. 
    %br
    To restore your changes to this page and continue editing, click Restore.

  %p.controls
    = link_to("Restore", admin_retreive_changes_path(object.class.name, object.id), :class => "btn retreive_changes", "data-param-name" => Gluttonberg::AutoSave.param_name_for(object.class.name))
    or
    = link_to("Cancel", admin_remove_autosaved_version_path(object.class.name, object.id), :class => "btn cancel_changes")

app/views/gluttonberg/admin/shared/_datetime_field.html.haml
.date-time-wrapper
  %span.date-time-input-wrapper
    = text_field_tag("#{unique_field_name}_date" , date , date_field_html_opts )
    = text_field_tag("#{unique_field_name}_time" , time , time_field_html_opts )
    = form.hidden_field("#{field_name}" ,  :class => "#{unique_field_name}")
    .clear

  %span.help-block
    %span.span2.datehelp DD/MM/YYYY
    %span.span2.timehelp HH:MM AM/PM

  .clear

%label.error{:class => "#{unique_field_name}_error"}
.clear
:javascript
  $(document).ready(function(){
    combine_datetime('#{unique_field_name}');
  });

app/views/gluttonberg/admin/shared/_previous_version_warning.html.haml
.restore-auto-save
  %h4
    Viewing older version
  %p
    You are currently viewing an older version of this #{@page_localization.blank? ? 'post' : 'page'}. Clicking update will publish this version, or #{link_to "click here", "?version="} to view the most recent revision.

app/views/gluttonberg/admin/shared/_version_alerts.html.haml
- page_or_post = @page.blank? ? 'post' : 'page'
- if can_publish
  - unless viewing_waiting_for_approval.blank?
    .restore-auto-save
      %h4
        Reviewing Version #{viewing_waiting_for_approval.version}: Submitted for approval 
        - unless viewing_waiting_for_approval.user.blank?
          by #{viewing_waiting_for_approval.user.full_name}
      %p
  - else
    - submitted_for_approval.each do |version|
      .restore-auto-save
        %h4
          Version #{version.version}: Waiting for approval
        %p
          - user_name = version.user.blank? ? 'someone' : version.user.full_name
          #{user_name} has submitted a new version of this #{page_or_post} for approval #{time_ago_in_words(version.updated_at)} ago.
          %br
          To review changes to this #{page_or_post} click Review.

        %p.controls
          = link_to("Review", "?version=#{version.version}", :class => "btn ")

  - your_revisions.each do |version|
    .restore-auto-save
      %h4
        Version #{version.version}: Unpublished revision
      %p
        It looks like previous edits you made to this #{page_or_post} have not yet been published. 
        %br
        To review your changes to this #{page_or_post} and continue editing, click Review.

      %p.controls
        = link_to("Review", "?version=#{version.version}", :class => "btn ")

app/views/gluttonberg/admin/shared/_version_dashboard_notifications.html.haml
- unless submitted_content.blank?
  .span3.waiting_for_approval
    .well
      %h3 Waiting for approval
      - submitted_content.each do |content|
        %p
          - unless content[0].blank?
            = truncate(content[0].to_s, :length => 30)
          = link_to("Review", content[1], :class => " ")
      - if more
        = link_to "More", admin_waiting_for_approval_path

app/views/gluttonberg/admin/shared/_version_listing.html.haml
.historycontrols
  .btn-group
    %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      Editing Version #{selected_version.version}
      %span.caret
    %ul.dropdown-menu
      - first_published = true
      - versions.each do |version|
        %li{:class => "#{version.version.to_s == selected.to_s ? 'active' : '' }"}
          - title = "Version #{version.version} (#{version.updated_at.strftime("%d/%m/%Y at %H:%M")} )" 
          - user = version.respond_to?(:user) ? version.user : nil
          - title += " by #{user.full_name}" unless user.blank?
          - if version.respond_to?(:version_status) && ((first_published && version.version_status == 'published') || version.version_status == 'submitted_for_approval' || version.version_status == 'declined')
            - if version.version_status == 'published'
              - first_published = false
            - title += " [<b>#{version.version_status.humanize}</b>]"


          = link_to  title.html_safe, "?version=#{version.version}"

.clear
%br/
%br/

app/views/gluttonberg/admin/shared/delete.html.haml
.container-fluid
  .row
    .span5.offset4
      %div#form.well
        = form_tag(@options[:url], :method => "delete") do
          %h1
            = @options[:title]
          - unless @options[:message].blank?
            %p.message
              = @options[:message].html_safe
          - unless @options[:warning].blank?
            %p.warning
              = @options[:warning].html_safe
          = hidden_field_tag "return_url" , @options[:return_url]
          %p.controls
            - unless @do_not_delete
              = submit_tag("Delete", :class => "btn btn-danger")
              or
              = link_to("<strong>Cancel</strong>".html_safe, @options[:return_url])
            - else
              = link_to("<strong>Ok</strong>".html_safe, @options[:return_url])

app/views/gluttonberg/admin/shared/generic.html.haml
.container-fluid
  .row
    .span5.offset4
      %div#form.well
        = form_tag(@options[:url]) do
          %h1
            = @options[:title]
          - unless @options[:message].blank?
            %p.message
              = @options[:message].html_safe
          - unless @options[:warning].blank?
            %p.warning
              = @options[:warning].html_safe

          %p.controls
            - unless @do_not_do
              = submit_tag(@name.capitalize)
              or
              = link_to("<strong>Cancel</strong>".html_safe, @options[:return_url])
            - else
              = link_to("<strong>Ok</strong>".html_safe, @options[:return_url])