config/routes.rb
Rails.application.routes.draw do
  mount_at = Gluttonberg::Engine.config.mount_at

  scope :module => 'gluttonberg' do
    namespace :admin do
      root :to => "main#index"
      get "waiting-for-approval" => "main#waiting_for_approval" , :as => :waiting_for_approval
      get "decline-content/:object_class/:version_id" => "main#decline_content" , :as => :decline_content
      

      scope :module => 'content' do
        controller :auto_save do
          match "/autosave/:model_name/:id" => :create , :as => :autosave
          get "/remove_autosaved_version/:model_name/:id" => :destroy , :as => :remove_autosaved_version
          get "/retreive_changes/:model_name/:id" => :retreive_changes , :as => :retreive_changes
        end

        get "/flagged_contents" => "flag#index" , :as => :flagged_contents
        get '/flagged_contents/moderation/:id/:moderation' => "flag#moderation", :as => :flagged_contents_moderation

        resources :pages do
          member do
            get 'delete'
            get 'duplicate'
            get 'collapse'
            get 'expand'
          end
          collection do
            post 'move' =>  :move_node, :as => :move
            post 'update_home', :as =>  :update_home
            match 'import'
            get 'export'
            get 'collapse_all'
            get 'expand_all'
          end

          resources :page_localizations
        end
        get "pages_list_for_tinymce" => "pages#pages_list_for_tinymce" , :as => :pages_list_for_tinymce

        post "/pages/move(.:format)" => "pages#move_node" , :as=> :page_move
        resources :galleries do
          get 'delete', :on => :member
        end
        post "/galleries/move(.:format)" => "galleries#move_node" , :as=> :gallery_move

      end

      # Settings
      scope :module => 'settings' do
        get 'history' => "global_history#index",      :as => :global_history
        resources :locales do
          get 'delete', :on => :member
        end

        resources :users do
          get 'delete', :on => :member
        end

        resources :configurations do
          get 'delete', :on => :member
        end

        resources :stylesheets do
          get 'delete', :on => :member
        end
        post "/stylesheets/move(.:format)" => "stylesheets#move_node" , :as=> :stylesheet_move

        resources :embeds do
          get 'delete', :on => :member
          get 'list-for-redactor' => :list_for_redactor, :on => :collection
        end
      end

      namespace :membership do
        root :to =>  "main#index"
        post "/groups/move(.:format)" => "groups#move_node" , :as=> :group_move
        get "members/export" => "members#export" , :as => :members_export
        get 'members/new_bulk'  => "members#new_bulk" , :as => :members_import
        post 'members/create_bulk' => "members#create_bulk" , :as => :members_bulk_create
        resources :members do
          get 'delete', :on => :member
          get 'welcome' , :on => :member
          get 'group/:id' => "members#group", :on => :collection, :as => :group_members
        end
        resources :groups do
          get 'delete', :on => :member
        end
      end


      scope :module => 'asset_library' do
        # asset library related routes
        resources :assets do
          get 'delete', :on => :member
          get 'crop', :on => :member
          post 'save_crop', :on => :member
        end
        get "library" => "assets#index" , :as => :library
        get "search_assets" => "assets#search" , :as => :library_search
        post "add_asset_using_ajax"  => "assets_ajax#create" , :as => :add_asset_using_ajax
        get "add_assets_in_bulk"  => "assets_bulk#add_assets_in_bulk" , :as => :add_assets_in_bulk
        post "create_assets_in_bulk"  => "assets_bulk#create_assets_in_bulk" , :as => :create_assets_in_bulk
        post "destroy_assets_in_bulk"  => "assets_bulk#destroy_assets_in_bulk" , :as => :destroy_assets_in_bulk
        get "browser"  => "assets#browser" , :as => :asset_browser
        get "browser-collection/:id"  => "assets_ajax#browser_collection" , :as => :asset_browser_collection
        get "filter_assets_by_date"  => "assets_ajax#filter_assets_by_date" , :as => :filter_assets_by_date
        get "assets/:category/page/:page"  => "assets#category" , :as => :asset_category
        get "collections/:id/page/:page"  => "collections#show" , :as => :asset_collection
        resources :collections  do
          get 'delete', :on => :member
        end
      end

      resources :password_resets

      get "login" => "user_sessions#new", :as => :login
      post "login" => "user_sessions#create"
      get "logout" => "user_sessions#destroy", :as => :logout
    end

    scope :module => 'public' do
      get "/user_asset/:hash/:id(/:thumb_name)" => "public_assets#show" , :as => :public_asset
      get "/_public/page" => "pages#show"
      get "/restrict_site_access" => "pages#restrict_site_access" , :as => :restrict_site_access
      get "sitemap" => "pages#sitemap" , :as => :sitemap

      get "/mark_as_flag/:flaggable_type/:flaggable_id" => "flag#new" , :as => :mark_as_flag
      post "/save_mark_as_flag" => "flag#create" , :as => :save_mark_as_flag
      get "(/:locale)/member/login" => "member_sessions#new" , :as => :member_login
      post "(/:locale)/member/login" => "member_sessions#create"  , :as => :member_login
      get "(/:locale)/member/logout" => "member_sessions#destroy", :as => :member_logout
      get "(/:locale)/member/confirm/:key" => "members#confirm", :as => :member_confirmation
      get "(/:locale)/member/resend_confirmation" => "members#resend_confirmation", :as => :member_resend_confirmation
      put "(/:locale)/member/profile" => "members#update"
      get "(/:locale)/member/profile" => "members#show", :as => :member_profile
      get "(/:locale)/member/profile/edit" => "members#edit", :as => :member_profile_edit

      scope "(/:locale)" do
        resources :members
        resources :member_password_resets
      end

      get 'stylesheets/:id' => "pages#stylesheets", :as =>  :stylesheets
    end


  end

  scope :module => 'gluttonberg' do
    scope :module => 'public' do
      get "*a" => "pages#error_404"
    end
  end
end

app/controllers/gluttonberg/admin/settings/configurations_controller.rb
# encoding: utf-8

module Gluttonberg
  module  Admin
    module Settings
      class ConfigurationsController < Gluttonberg::Admin::BaseController
        before_filter :find_setting, :only => [:delete, :edit, :update, :destroy]
        before_filter :authorize_user
        before_filter :authorize_user_for_create_or_destroy, :only => [:delete, :new, :create, :destroy]
        record_history :@setting

        # Confuguration/settings listing page
        def index
          # grab multisite settings
          @multisite = Rails.configuration.multisite.kind_of?(Hash)
          # grab all global settings
          @cms_settings = Setting.where("site is NULL or site=''").order("row asc").all
          # grab all settings for all sites
          @site_wise_settings = {}
          if @multisite
            Rails.configuration.multisite.each do |key, val|
              @site_wise_settings[key] = Setting.where(:site => key).order("row asc").all
            end
          end
          @settings = Setting.order("row asc").all
          @current_home_page_id  = Page.home_page.id unless Page.home_page.blank?
          @pages = Page.all
        end

        def new
          @setting = Setting.new
        end

        def edit
        end

        def create
          @setting = Setting.new(params["gluttonberg_setting"])
          count = Setting.all.length
          @setting.row = count + 1
          if @setting.save
            flash[:notice] = "The configuration was successfully created."
            redirect_to admin_configurations_path
          else
            render :new
          end
        end

        def update
          if params.has_key? "gluttonberg/setting"
            params[:gluttonberg_setting] = params["gluttonberg/setting"]
          end
          if @setting.update_attributes(params[:gluttonberg_setting])
            if request.xhr?
              render :text => @setting.value
            else
              flash[:notice] = "The configuration was successfully updated."
              format.html redirect_to admin_configurations_path
            end
          else
            flash[:error] = "Sorry, The configuration could not be updated."
            render :edit
          end
        end


        def delete
          display_delete_confirmation(
            :title      => "Delete “#{@setting.name}” configuration?",
            :url        => admin_configuration_path(@setting),
            :return_url => admin_configurations_path
          )
        end

        def destroy
          generic_destroy(@setting, {
            :name => "setting",
            :success_path => admin_configurations_path,
            :failure_path => admin_configurations_path
          })
        end

        private

          def find_setting
            @setting = Setting.where(:id => params[:id]).first
            raise ActiveRecord::RecordNotFound  unless @setting
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Setting
          end

          def authorize_user_for_create_or_destroy
            authorize! :create_or_destroy, Gluttonberg::Setting
          end

      end # ConfigurationsController
    end # Settings
  end #admin
end # Gluttonberg

app/controllers/gluttonberg/admin/settings/embeds_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module Settings
      # this controller manages embed code (shortcodes). 
      # wysiwyg snippets which can be embed in other content.
      class EmbedsController < Gluttonberg::Admin::BaseController
        before_filter :find_embed, :only => [:edit, :update, :delete, :destroy]
        before_filter :authorize_user , :except => [:destroy , :delete]
        before_filter :authorize_user_for_destroy , :only => [:destroy , :delete]
        record_history :@embed

        def index
          @embeds = Embed.order("created_at ASC")
        end

        def new
          @embed = Embed.new
        end

        def create
          @embed = Embed.new(params[:gluttonberg_embed])
          generic_create(@embed, {
            :name => "embed",
            :success_path => admin_embeds_path
          })
        end

        def edit
        end

        def update
          @embed.assign_attributes(params[:gluttonberg_embed])
          generic_update(@embed, {
            :name => "embed",
            :success_path => admin_embeds_path
          })
        end

        def delete
          display_delete_confirmation(
            :title      => "Delete Embed '#{@embed.name}'?",
            :url        => admin_embed_path(@embed),
            :return_url => admin_embeds_path,
            :warning    => ""
          )
        end

        def destroy
          generic_destroy(@embed, {
            :name => "embed",
            :success_path => admin_embeds_path,
            :failure_path => admin_embeds_path
          })
        end

        def list_for_redactor
          @embeds = Embed.order("created_at ASC")
          render :layout => false
        end

        protected

          def find_embed
            @embed = Embed.where(:id  => params[:id]).first
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Embed
          end

          def authorize_user_for_destroy
            authorize! :destroy, Gluttonberg::Embed
          end
      end # controller
    end
  end
end

app/controllers/gluttonberg/admin/settings/global_history_controller.rb
module Gluttonberg
  module Admin
    module Settings  
          class GlobalHistoryController < Gluttonberg::Admin::BaseController
            def index
              @feeds = Feed.order("created_at DESC").paginate(:page => params[:page] , :per_page =>Gluttonberg::Setting.get_setting("number_of_per_page_items"))
            end
          end
      end    
  end
end

app/controllers/gluttonberg/admin/settings/locales_controller.rb
# encoding: utf-8

module Gluttonberg
  module  Admin
    module Settings
      class LocalesController < Gluttonberg::Admin::BaseController
        before_filter :find_locale, :only => [:delete, :edit, :update, :destroy]
        before_filter :authorize_user
        record_history :@locale

        def index
          @locales = Locale.all
        end

        def new
          @locale   = Locale.new
        end

        def edit
        end

        def delete
          display_delete_confirmation(
            :title      => "Delete “#{@locale.name}” locale?",
            :url        => admin_locale_path(@locale),
            :return_url => admin_locales_path ,
            :warning    => "Page localizations of this locale will also be deleted."
          )
        end

        def create
          @locale = Locale.new(params[:gluttonberg_locale])
          generic_create(@locale, {
            :name => "locale",
            :success_path => admin_locales_path
          })
        end

        def update
          @locale.assign_attributes(params["gluttonberg_locale"]) || !@locale.dirty?
          generic_update(@locale, {
            :name => "locale",
            :success_path => admin_locales_path
          })
        end

        def destroy
          generic_destroy(@locale, {
            :name => "locale",
            :success_path => admin_locales_path,
            :failure_path => admin_locales_path
          })
        end

        private

          def find_locale
            @locale = Locale.where(:id  => params[:id]).first
            raise ActiveRecord::RecordNotFound  unless @locale
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Locale
          end

      end
    end
  end
end

app/controllers/gluttonberg/admin/settings/stylesheets_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module Settings
      # CMS based stylesheets management
      class StylesheetsController < Gluttonberg::Admin::BaseController
        drag_tree Stylesheet , :route_name => :admin_stylesheet_move
        before_filter :find_stylesheet, :only => [:edit, :update, :delete, :destroy]
        before_filter :authorize_user , :except => [:destroy , :delete]
        before_filter :authorize_user_for_destroy , :only => [:destroy , :delete]
        record_history :@stylesheet

        def index
          @stylesheets = Stylesheet.order("position ASC")
        end

        def new
          @stylesheet = Stylesheet.new
        end

        def create
          @stylesheet = Stylesheet.new(params[:gluttonberg_stylesheet])
          generic_create(@stylesheet, {
            :name => "stylesheet",
            :success_path => admin_stylesheets_path
          })
        end

        def edit
          unless params[:version].blank?
            @version = params[:version]
            @stylesheet.revert_to(@version)
          end
        end

        def update
          @stylesheet.assign_attributes(params[:gluttonberg_stylesheet])
          generic_update(@stylesheet, {
            :name => "stylesheet",
            :success_path => admin_stylesheets_path
          })
        end

        def delete
          display_delete_confirmation(
            :title      => "Delete Stylesheet '#{@stylesheet.name}'?",
            :url        => admin_stylesheet_path(@stylesheet),
            :return_url => admin_stylesheets_path,
            :warning    => ""
          )
        end

        def destroy
          generic_destroy(@stylesheet, {
            :name => "stylesheet",
            :success_path => admin_stylesheets_path,
            :failure_path => admin_stylesheets_path
          })
        end


        protected

          def find_stylesheet
            @stylesheet = Stylesheet.where(:id  => params[:id]).first
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Stylesheet
          end

          def authorize_user_for_destroy
            authorize! :destroy, Gluttonberg::Stylesheet
          end

      end
    end
  end
end

app/views/gluttonberg/admin/settings/configurations/_form.html.haml
.row-fluid
  = form_for(@setting, :url => url) do  |f|
    = gb_error_messages_for(@setting)
    .span5
      %legend
        Setting
      - if @setting.delete_able
        %p
          = f.label :name ,  "Setting Name"
          = f.text_field(:name)
        %p
          = f.label :value ,  "Setting Value"
          = render :partial => "value_tag" , :locals => { :f => f}
        %p
          = f.label :values_list ,  "Setting Value List (; seperated) (optional)"
          = f.text_area(:values_list , :class => "large tall")
        %p
          = f.label :help
          = f.text_area(:help , :class => "large tall")
      - else
        %p
          = f.label :value , @setting.user_friendly_name
          = render :partial => "value_tag" , :locals => { :f => f}
        %p
          %small= @setting.help

      %p
        = form_controls(admin_configurations_path)

app/views/gluttonberg/admin/settings/configurations/_settings_table.html.haml
%table{:cellspacing => 0, :cellpadding => 0, :summary => "List of Settings", :class => "table table-bordered"}
  %thead
    %tr
      %th Name
      %th Value (Click to edit)
      - if @has_deletable_settings
        %th.controls Controls
  %tbody
    - unless @multisite
      %tr{ :class => ""}
        %td.first_column
          Select Home Page
        %td.second_column
          = select_tag :home , options_for_select(pages_lists_options , selected = @current_home_page_id.to_s )  ,  { :include_blank => true , :class => "home_page_setting_dropdown chzn-select"  , :rel => update_home_admin_pages_path  }
          = image_tag("/assets/gb_spinner.gif" , :id => "progress_home_page" , :style => "display:none")
        - if @has_deletable_settings
          %td.controls

    - for setting in settings
      %tr{ :class => "#{cycle("even", "odd")}"}
        %td.first_column{ :style => 'width:220px' }
          = setting.user_friendly_name
        %td.second_column
          - unless setting.help.blank?
            %em{ :style => "font-size: 90%;" }= setting.help
            %span{:style => "height: 10px; display: block;"}

          - if setting.dropdown_required?
            = select_tag(:value , options_for_select( setting.parsed_values_list_for_dropdown , setting.value  ) , { :include_blank => true , :data_id => setting.id  , :rel => admin_configuration_path( setting) , :class => "setting_dropdown"   })
          - elsif setting.name == "fb_icon"
            = asset_browser_tag( "gluttonberg_setting[value]" ,  opts = {:button_class => "logo_setting button" , :filter => "image" ,  :id => "gluttonberg_setting_fb_icon", :asset_id => setting.value  , :data_url => admin_configuration_path( setting) } )
          - elsif setting.name == "backend_logo"
            = asset_browser_tag( "gluttonberg_setting[value]" ,  opts = {:button_class => "logo_setting button" , :filter => "image" ,  :id => "gluttonberg_setting_backend_logo", :asset_id => setting.value  , :data_url => admin_configuration_path( setting)  } )

          - else
            = gb_editable_field setting, :value , :update_url => admin_configuration_path(setting)

          = image_tag("/assets/gb_spinner.gif" , :id => "progress_#{setting.id}" , :style => "display:none")
        - if @has_deletable_settings
          %td.controls
            - if setting.delete_able
              = link_to 'Delete', delete_admin_configuration_path(setting)

app/views/gluttonberg/admin/settings/configurations/_value_tag.html.haml
- if @setting.dropdown_required?
  = f.select(:value , options_for_select( @setting.parsed_values_list_for_dropdown , @setting.value  ) )
- else
  = f.text_area(:value,  :class => "large tall")

app/views/gluttonberg/admin/settings/configurations/edit.html.haml
- @window_title = "Settings"
- @page_title = "#{link_to "Settings", admin_settings_path} > #{link_to("Configuration", admin_configurations_path)} > Edit settings"

= render :partial => "form" , :locals => { :url => admin_configuration_path( @setting) }

app/views/gluttonberg/admin/settings/configurations/index.html.haml
- @window_title = "Settings"
- @page_title = "Configuration"

- @has_deletable_settings = Gluttonberg::Setting.has_deletable_settings?
.row-fluid
  = render :partial => "/gluttonberg/admin/settings/main/sidebar"
  .span9
    .row-fluid
      .page-header
        %h1
          = @page_title.html_safe
      .subnav
        = sub_nav do
          - if can? :create_or_destroy, Gluttonberg::Setting
            = nav_link('Add New Setting', new_admin_configuration_path)

      
      - if @multisite
        - Rails.configuration.multisite.each do |key, val|
          %h2
            #{val} Configuration
  
          = render :partial => "settings_table", :locals => {:settings => @site_wise_settings[key]}
      

        %h2
          Global Configuration
          
      = render :partial => "settings_table", :locals => {:settings => @cms_settings}

app/views/gluttonberg/admin/settings/configurations/new.html.haml
- @window_title = "Settings"
- @page_title = "#{link_to "Configuration", admin_configurations_path} > Add a new setting"

.row-fluid
  = render :partial => "/gluttonberg/admin/settings/main/sidebar"
  .span9
    .row-fluid
      .page-header
        %h1
          = @page_title.html_safe
      .subnav
      = render :partial => "form", :locals => { :url => admin_configurations_path }